name: Documentation

on:
  push:
    branches: ['main']

  workflow_dispatch:

concurrency:
  group: 'deploy'
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install zensical
      - name: Build
        run: zensical build --clean
      - name: Set up Node
        uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          preCommands: wrangler pages project create indelible-static --production-branch=main || true
          command: pages deploy site --project-name=indelible-docs
